apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  # Controls how many suites are executed at the same time (sauce test env only).
  concurrency: 10
  metadata:
    name: Testing Espresso Support
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
espresso:
  app: ./todo-android/app/build/outputs/apk/debug/app-debug.apk
  testApp: ./todo-android/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
suites:
  - name: "saucy barista - combined"
    testOptions:
      class:
        - com.example.todo.ToDoAddAndDeleteTest
    emulators:
      - name: "Google Pixel C GoogleAPI Emulator"
        orientation: landscape
        platformVersions:
          - "8.1"
    devices:
      - id: Huawei_P10_real
      - name: "Huawei.*"
        platformVersion: 8.0.0
  - name: "saucy barista - package"
    testOptions:
      package: com.example.todo.persistence.MainPresenterTest
    emulators:
      - name: "Android GoogleApi Emulator"
        platformVersions:
          - "11.0"
  - name: "saucy barista - test size"
    testOptions:
      size: small
    emulators:
      - name: "Android GoogleApi Emulator"
        platformVersions:
          - "11.0"

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - junit.xml
    directory: ./artifacts/
